services:
  app:
    container_name: 'wpp-sticker-bot'
    build: .
    ports:
      - "3000:3000"
    image: wpp-sticker-bot:latest
    restart: unless-stopped
    environment:
      NODE_ENV: development
    volumes:
      - wwebjsauth:/app/.wwebjs_auth
      - wwebjscache:/app/.wwebjs_cache

volumes:
  wwebjsauth:
  wwebjscache: