services:
  app:
    build: .
    ports:
      - "3000:3000"
    image: wpp-finance:latest
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - wwebjsauth:/app/.wwebjs_auth
      - wwebjscache:/app/.wwebjs_cache

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/data
    networks:
      - app-network

volumes:
  postgres-data:
  wwebjsauth:
  wwebjscache:

networks:
  app-network:
    driver: bridge